<a href="https://colab.research.google.com/github/asanaa-data/asanaa-data/blob/main/Copy_of_Numpy_Catch_up.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Creating Arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)



## Initial Placeholders

In [ ]:
np.zeros((3,4)) #Create on  array of zero
np.ones((2,3,4),dtype=np.int16)#Create an array of ones


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## Create a NumPy ndarray Object


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [ ]:
#Access Array Elements
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
#Array Indexing
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [ ]:
# NumPy Array Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [ ]:
arr = np.array([1, 4, 5, 4, 9, 6, 7])
print(arr[::2])

[1 5 9 7]


In [ ]:
# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


## Data Types in NumPy

Below is a list of all data types in NumPy and the characters used to represent them.
7/4/24, 6:18 PM Numpy Catch_up.ipynb - Colab

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [ ]:
# Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# What if a Value Can Not Be Converted?

arr = np.array(['a', '2', '3'], dtype='i')




ValueError: invalid literal for int() with base 10: 'a'


## Converting Data Type on Existing Arrays


The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for
integer.
arr

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Change data type from integer to boolean:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
# NumPy Array Copy vs View
arr = np.array([1, 2, 3, 4, 5])
x_copy = arr.copy()
x_view = arr.view()
arr[0] = 42
print(arr)
print("option for copy",x_copy)
print("option for view",x_view)

[42  2  3  4  5]
option for copy [1 2 3 4 5]
option for view [42  2  3  4  5]


In [ ]:
# NumPy Array Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,6)
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,18,19,20,21,22,23,24])
newarr = arr.reshape(3, 2, 4)
print(newarr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2,-1)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2,-1)
newarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Array Iterating


In [ ]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#Example
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used from very basic
#to very advanced iterations
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Joining NumPy Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Sorting Arrays


In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr = np.array([[3, 2, 4,5], [5, 0, 1,6]])
print(np.flip(arr))

[[6 1 0 5]
 [5 4 2 3]]


In [ ]:
# Filtering Arrays
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [ ]:
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)

[False, False, True, True]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


## Control Flows

In [ ]:
for letter in "Python":
# continue when letter is 'h'
  if letter == "h":
    continue
  print("Current Letter :", letter)

Current Letter : P
Current Letter : y
Current Letter : t
Current Letter : o
Current Letter : n


In [ ]:
marks = 80
result = ""
if marks < 30:
  result = "Failed"
elif marks > 75:
  result = "Passed with distinction"
else:
  result = "Passed"
print(result)

Passed with distinction


In [ ]:
# break statement
x = 0
while x < 10:
  print("x:", x)
  if x == 5:
    print("Breaking...")
    break
  x += 1
print("End")

x: 0
x: 1
x: 2
x: 3
x: 4
x: 5
Breaking...
End


In [ ]:
name = 'Debora'
if name == 'Debora':

  print('Hi, Debora')
# Hi, Debora
if name != 'George':
  print('You are not George')

Hi, Debora
You are not George


In [ ]:
name = 'Debora'
if name == 'George':
  print('Hi, George.')
else:
  print('You are not George')

You are not George


In [ ]:
name = 'George'
if name == 'Debora':
  print('Hi Debora!')
elif name == 'George':
  print('Hi George!')
# Hi George!


Hi George!


In [ ]:
name = 'Antony'
if name == 'Debora':
  print('Hi Debora!')
elif name == 'George':
  print('Hi George!')
else:
  print('Who are you?')
# Who are you?

Who are you?
